# Generated by Django 2.0 on 2018-09-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0, verbose_name='番号'),
            preserve_default=False,
        ),
    ]
